/*
	This file is generated by matched_filter_gen.py script written by Brandon Hippe
	Arguments:
	+-----------------------+-------------------+
	|        Argument       |       Value       |
	+-----------------------+-------------------+
	|       adc_width       |         4         |
	|          fsym         |      1000000      |
	| matched_filter_output | matched_filter.sv |
	|          amp          |         15        |
	|        clk_freq       |      16000000     |
	|         ifreq         |     1250000.0     |
	+-----------------------+-------------------+
*/
(* keep_hierarchy = "yes" *)
(* max_fanout = 16 *)
module matched_filter #(
    parameter SAMPLE_RATE = 16,
    parameter DATA_WIDTH = 4
) (
    input logic clk,
    input logic en,
    input logic resetn,

    input logic signed [DATA_WIDTH-1:0] i_data, q_data,
    output logic demodulated_bit
);

    localparam PIPELINE_STAGES = 3;

    // localparam TEMPLATE_WIDTH = 5;
    // localparam PROD_WIDTH = DATA_WIDTH + TEMPLATE_WIDTH;
    // localparam PROD_SUM_WIDTH = $clog2(SAMPLE_RATE) + PROD_WIDTH;
    // localparam SQR_WIDTH = 2 * PROD_SUM_WIDTH;
    // localparam SCORE_WIDTH = SQR_WIDTH + 1;



    localparam TEMPLATE_WIDTH = 5;
    localparam PROD_WIDTH = 8;                                // Was 9
    localparam PROD_SUM_WIDTH = 11;                           // Was 13, save 2 bits
    localparam SQR_WIDTH = 22;                                // Was 26, save 4 bits
    localparam SCORE_WIDTH = 23;                              // Was 27, save 4 bits

/*
    +--------------+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
    |   Template   |  0 |  1 |  2 |  3 |   4 |   5 |   6 |   7 |   8 |   9 |  10 |  11 |  12 |  13 |  14 |  15 |
    +--------------+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
    | 0 Template I | 15 | 14 | 11 |  6 |   0 |  -6 | -11 | -14 | -15 | -14 | -11 |  -6 |   0 |   6 |  11 |  14 |
    | 0 Template Q |  0 |  6 | 11 | 14 |  15 |  14 |  11 |   6 |   0 |  -6 | -11 | -14 | -15 | -14 | -11 |  -6 |
    | 1 Template I | 15 | 12 |  6 | -3 | -11 | -15 | -14 |  -8 |   0 |   8 |  14 |  15 |  11 |   3 |  -6 | -12 |
    | 1 Template Q |  0 |  8 | 14 | 15 |  11 |   3 |  -6 | -12 | -15 | -12 |  -6 |   3 |  11 |  15 |  14 |   8 |
    +--------------+----+----+----+----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+-----+
*/

        // Define buffer for input data
        (* max_fanout = 8 *)
    logic signed [SAMPLE_RATE-1:0][DATA_WIDTH-1:0] i_buffer, q_buffer;
    always_ff @(posedge clk or negedge resetn) begin
        if (~resetn) begin
            i_buffer <= 0;
            q_buffer <= 0;
        end else if (en) begin
            i_buffer <= {i_buffer[SAMPLE_RATE-2:0], i_data};
            q_buffer <= {q_buffer[SAMPLE_RATE-2:0], q_data};
        end
    end
    // STAGE 1: Individual Products

    // WIRES: Combinational outputs (computed every cycle)
    logic signed [PROD_WIDTH-1:0] s1_low_i_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_low_q_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_low_i_q_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_low_q_q_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_high_i_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_high_q_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_high_i_q_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_high_q_q_prod [0:15];

    // REGISTERS: Store the wire values (pipeline stage boundary)
    logic signed [PROD_WIDTH-1:0] s1_reg_low_i_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_low_q_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_low_i_q_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_low_q_q_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_high_i_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_high_q_i_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_high_i_q_prod [0:15];
    logic signed [PROD_WIDTH-1:0] s1_reg_high_q_q_prod [0:15];


    // STAGE 1 COMBINATIONAL: Individual Products
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 15, 14, 11, 6, 0, -6, -11, -14, -15, -14, -11, -6, 0, 6, 11, 14
        s1_low_i_i_prod[15] = (i_buffer[15] << 0) + (i_buffer[15] << 1) + (i_buffer[15] << 2) + (i_buffer[15] << 3); // *15
        s1_low_i_i_prod[14] = (i_buffer[14] << 1) + (i_buffer[14] << 2) + (i_buffer[14] << 3); // *14
        s1_low_i_i_prod[13] = (i_buffer[13] << 0) + (i_buffer[13] << 1) + (i_buffer[13] << 3); // *11
        s1_low_i_i_prod[12] = (i_buffer[12] << 1) + (i_buffer[12] << 2); // *6
        s1_low_i_i_prod[11] = 0; // *0
        s1_low_i_i_prod[10] = -((i_buffer[10] << 1) + (i_buffer[10] << 2)); // *-6
        s1_low_i_i_prod[9] = -((i_buffer[9] << 0) + (i_buffer[9] << 1) + (i_buffer[9] << 3)); // *-11
        s1_low_i_i_prod[8] = -((i_buffer[8] << 1) + (i_buffer[8] << 2) + (i_buffer[8] << 3)); // *-14
        s1_low_i_i_prod[7] = -((i_buffer[7] << 0) + (i_buffer[7] << 1) + (i_buffer[7] << 2) + (i_buffer[7] << 3)); // *-15
        s1_low_i_i_prod[6] = -((i_buffer[6] << 1) + (i_buffer[6] << 2) + (i_buffer[6] << 3)); // *-14
        s1_low_i_i_prod[5] = -((i_buffer[5] << 0) + (i_buffer[5] << 1) + (i_buffer[5] << 3)); // *-11
        s1_low_i_i_prod[4] = -((i_buffer[4] << 1) + (i_buffer[4] << 2)); // *-6
        s1_low_i_i_prod[3] = 0; // *0
        s1_low_i_i_prod[2] = (i_buffer[2] << 1) + (i_buffer[2] << 2); // *6
        s1_low_i_i_prod[1] = (i_buffer[1] << 0) + (i_buffer[1] << 1) + (i_buffer[1] << 3); // *11
        s1_low_i_i_prod[0] = (i_buffer[0] << 1) + (i_buffer[0] << 2) + (i_buffer[0] << 3); // *14
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 2: LOW TEMPLATE Q × I (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 15, 14, 11, 6, 0, -6, -11, -14, -15, -14, -11, -6, 0, 6, 11, 14
        s1_low_q_i_prod[15] = (q_buffer[15] << 0) + (q_buffer[15] << 1) + (q_buffer[15] << 2) + (q_buffer[15] << 3); // *15
        s1_low_q_i_prod[14] = (q_buffer[14] << 1) + (q_buffer[14] << 2) + (q_buffer[14] << 3); // *14
        s1_low_q_i_prod[13] = (q_buffer[13] << 0) + (q_buffer[13] << 1) + (q_buffer[13] << 3); // *11
        s1_low_q_i_prod[12] = (q_buffer[12] << 1) + (q_buffer[12] << 2); // *6
        s1_low_q_i_prod[11] = 0; // *0
        s1_low_q_i_prod[10] = -((q_buffer[10] << 1) + (q_buffer[10] << 2)); // *-6
        s1_low_q_i_prod[9] = -((q_buffer[9] << 0) + (q_buffer[9] << 1) + (q_buffer[9] << 3)); // *-11
        s1_low_q_i_prod[8] = -((q_buffer[8] << 1) + (q_buffer[8] << 2) + (q_buffer[8] << 3)); // *-14
        s1_low_q_i_prod[7] = -((q_buffer[7] << 0) + (q_buffer[7] << 1) + (q_buffer[7] << 2) + (q_buffer[7] << 3)); // *-15
        s1_low_q_i_prod[6] = -((q_buffer[6] << 1) + (q_buffer[6] << 2) + (q_buffer[6] << 3)); // *-14
        s1_low_q_i_prod[5] = -((q_buffer[5] << 0) + (q_buffer[5] << 1) + (q_buffer[5] << 3)); // *-11
        s1_low_q_i_prod[4] = -((q_buffer[4] << 1) + (q_buffer[4] << 2)); // *-6
        s1_low_q_i_prod[3] = 0; // *0
        s1_low_q_i_prod[2] = (q_buffer[2] << 1) + (q_buffer[2] << 2); // *6
        s1_low_q_i_prod[1] = (q_buffer[1] << 0) + (q_buffer[1] << 1) + (q_buffer[1] << 3); // *11
        s1_low_q_i_prod[0] = (q_buffer[0] << 1) + (q_buffer[0] << 2) + (q_buffer[0] << 3); // *14
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 3: LOW TEMPLATE I × Q (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 0, 6, 11, 14, 15, 14, 11, 6, 0, -6, -11, -14, -15, -14, -11, -6
        s1_low_i_q_prod[15] = 0; // *0
        s1_low_i_q_prod[14] = (i_buffer[14] << 1) + (i_buffer[14] << 2); // *6
        s1_low_i_q_prod[13] = (i_buffer[13] << 0) + (i_buffer[13] << 1) + (i_buffer[13] << 3); // *11
        s1_low_i_q_prod[12] = (i_buffer[12] << 1) + (i_buffer[12] << 2) + (i_buffer[12] << 3); // *14
        s1_low_i_q_prod[11] = (i_buffer[11] << 0) + (i_buffer[11] << 1) + (i_buffer[11] << 2) + (i_buffer[11] << 3); // *15
        s1_low_i_q_prod[10] = (i_buffer[10] << 1) + (i_buffer[10] << 2) + (i_buffer[10] << 3); // *14
        s1_low_i_q_prod[9] = (i_buffer[9] << 0) + (i_buffer[9] << 1) + (i_buffer[9] << 3); // *11
        s1_low_i_q_prod[8] = (i_buffer[8] << 1) + (i_buffer[8] << 2); // *6
        s1_low_i_q_prod[7] = 0; // *0
        s1_low_i_q_prod[6] = -((i_buffer[6] << 1) + (i_buffer[6] << 2)); // *-6
        s1_low_i_q_prod[5] = -((i_buffer[5] << 0) + (i_buffer[5] << 1) + (i_buffer[5] << 3)); // *-11
        s1_low_i_q_prod[4] = -((i_buffer[4] << 1) + (i_buffer[4] << 2) + (i_buffer[4] << 3)); // *-14
        s1_low_i_q_prod[3] = -((i_buffer[3] << 0) + (i_buffer[3] << 1) + (i_buffer[3] << 2) + (i_buffer[3] << 3)); // *-15
        s1_low_i_q_prod[2] = -((i_buffer[2] << 1) + (i_buffer[2] << 2) + (i_buffer[2] << 3)); // *-14
        s1_low_i_q_prod[1] = -((i_buffer[1] << 0) + (i_buffer[1] << 1) + (i_buffer[1] << 3)); // *-11
        s1_low_i_q_prod[0] = -((i_buffer[0] << 1) + (i_buffer[0] << 2)); // *-6
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 4: LOW TEMPLATE Q × Q (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 0, 6, 11, 14, 15, 14, 11, 6, 0, -6, -11, -14, -15, -14, -11, -6
        s1_low_q_q_prod[15] = 0; // *0
        s1_low_q_q_prod[14] = (q_buffer[14] << 1) + (q_buffer[14] << 2); // *6
        s1_low_q_q_prod[13] = (q_buffer[13] << 0) + (q_buffer[13] << 1) + (q_buffer[13] << 3); // *11
        s1_low_q_q_prod[12] = (q_buffer[12] << 1) + (q_buffer[12] << 2) + (q_buffer[12] << 3); // *14
        s1_low_q_q_prod[11] = (q_buffer[11] << 0) + (q_buffer[11] << 1) + (q_buffer[11] << 2) + (q_buffer[11] << 3); // *15
        s1_low_q_q_prod[10] = (q_buffer[10] << 1) + (q_buffer[10] << 2) + (q_buffer[10] << 3); // *14
        s1_low_q_q_prod[9] = (q_buffer[9] << 0) + (q_buffer[9] << 1) + (q_buffer[9] << 3); // *11
        s1_low_q_q_prod[8] = (q_buffer[8] << 1) + (q_buffer[8] << 2); // *6
        s1_low_q_q_prod[7] = 0; // *0
        s1_low_q_q_prod[6] = -((q_buffer[6] << 1) + (q_buffer[6] << 2)); // *-6
        s1_low_q_q_prod[5] = -((q_buffer[5] << 0) + (q_buffer[5] << 1) + (q_buffer[5] << 3)); // *-11
        s1_low_q_q_prod[4] = -((q_buffer[4] << 1) + (q_buffer[4] << 2) + (q_buffer[4] << 3)); // *-14
        s1_low_q_q_prod[3] = -((q_buffer[3] << 0) + (q_buffer[3] << 1) + (q_buffer[3] << 2) + (q_buffer[3] << 3)); // *-15
        s1_low_q_q_prod[2] = -((q_buffer[2] << 1) + (q_buffer[2] << 2) + (q_buffer[2] << 3)); // *-14
        s1_low_q_q_prod[1] = -((q_buffer[1] << 0) + (q_buffer[1] << 1) + (q_buffer[1] << 3)); // *-11
        s1_low_q_q_prod[0] = -((q_buffer[0] << 1) + (q_buffer[0] << 2)); // *-6
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 5: HIGH TEMPLATE I × I (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 15, 12, 6, -3, -11, -15, -14, -8, 0, 8, 14, 15, 11, 3, -6, -12
        s1_high_i_i_prod[15] = (i_buffer[15] << 0) + (i_buffer[15] << 1) + (i_buffer[15] << 2) + (i_buffer[15] << 3); // *15
        s1_high_i_i_prod[14] = (i_buffer[14] << 2) + (i_buffer[14] << 3); // *12
        s1_high_i_i_prod[13] = (i_buffer[13] << 1) + (i_buffer[13] << 2); // *6
        s1_high_i_i_prod[12] = -((i_buffer[12] << 0) + (i_buffer[12] << 1)); // *-3
        s1_high_i_i_prod[11] = -((i_buffer[11] << 0) + (i_buffer[11] << 1) + (i_buffer[11] << 3)); // *-11
        s1_high_i_i_prod[10] = -((i_buffer[10] << 0) + (i_buffer[10] << 1) + (i_buffer[10] << 2) + (i_buffer[10] << 3)); // *-15
        s1_high_i_i_prod[9] = -((i_buffer[9] << 1) + (i_buffer[9] << 2) + (i_buffer[9] << 3)); // *-14
        s1_high_i_i_prod[8] = -(i_buffer[8] << 3); // *-8
        s1_high_i_i_prod[7] = 0; // *0
        s1_high_i_i_prod[6] = (i_buffer[6] << 3); // *8
        s1_high_i_i_prod[5] = (i_buffer[5] << 1) + (i_buffer[5] << 2) + (i_buffer[5] << 3); // *14
        s1_high_i_i_prod[4] = (i_buffer[4] << 0) + (i_buffer[4] << 1) + (i_buffer[4] << 2) + (i_buffer[4] << 3); // *15
        s1_high_i_i_prod[3] = (i_buffer[3] << 0) + (i_buffer[3] << 1) + (i_buffer[3] << 3); // *11
        s1_high_i_i_prod[2] = (i_buffer[2] << 0) + (i_buffer[2] << 1); // *3
        s1_high_i_i_prod[1] = -((i_buffer[1] << 1) + (i_buffer[1] << 2)); // *-6
        s1_high_i_i_prod[0] = -((i_buffer[0] << 2) + (i_buffer[0] << 3)); // *-12
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 6: HIGH TEMPLATE Q × I (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 15, 12, 6, -3, -11, -15, -14, -8, 0, 8, 14, 15, 11, 3, -6, -12
        s1_high_q_i_prod[15] = (q_buffer[15] << 0) + (q_buffer[15] << 1) + (q_buffer[15] << 2) + (q_buffer[15] << 3); // *15
        s1_high_q_i_prod[14] = (q_buffer[14] << 2) + (q_buffer[14] << 3); // *12
        s1_high_q_i_prod[13] = (q_buffer[13] << 1) + (q_buffer[13] << 2); // *6
        s1_high_q_i_prod[12] = -((q_buffer[12] << 0) + (q_buffer[12] << 1)); // *-3
        s1_high_q_i_prod[11] = -((q_buffer[11] << 0) + (q_buffer[11] << 1) + (q_buffer[11] << 3)); // *-11
        s1_high_q_i_prod[10] = -((q_buffer[10] << 0) + (q_buffer[10] << 1) + (q_buffer[10] << 2) + (q_buffer[10] << 3)); // *-15
        s1_high_q_i_prod[9] = -((q_buffer[9] << 1) + (q_buffer[9] << 2) + (q_buffer[9] << 3)); // *-14
        s1_high_q_i_prod[8] = -(q_buffer[8] << 3); // *-8
        s1_high_q_i_prod[7] = 0; // *0
        s1_high_q_i_prod[6] = (q_buffer[6] << 3); // *8
        s1_high_q_i_prod[5] = (q_buffer[5] << 1) + (q_buffer[5] << 2) + (q_buffer[5] << 3); // *14
        s1_high_q_i_prod[4] = (q_buffer[4] << 0) + (q_buffer[4] << 1) + (q_buffer[4] << 2) + (q_buffer[4] << 3); // *15
        s1_high_q_i_prod[3] = (q_buffer[3] << 0) + (q_buffer[3] << 1) + (q_buffer[3] << 3); // *11
        s1_high_q_i_prod[2] = (q_buffer[2] << 0) + (q_buffer[2] << 1); // *3
        s1_high_q_i_prod[1] = -((q_buffer[1] << 1) + (q_buffer[1] << 2)); // *-6
        s1_high_q_i_prod[0] = -((q_buffer[0] << 2) + (q_buffer[0] << 3)); // *-12
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 7: HIGH TEMPLATE I × Q (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 0, 8, 14, 15, 11, 3, -6, -12, -15, -12, -6, 3, 11, 15, 14, 8
        s1_high_i_q_prod[15] = 0; // *0
        s1_high_i_q_prod[14] = (i_buffer[14] << 3); // *8
        s1_high_i_q_prod[13] = (i_buffer[13] << 1) + (i_buffer[13] << 2) + (i_buffer[13] << 3); // *14
        s1_high_i_q_prod[12] = (i_buffer[12] << 0) + (i_buffer[12] << 1) + (i_buffer[12] << 2) + (i_buffer[12] << 3); // *15
        s1_high_i_q_prod[11] = (i_buffer[11] << 0) + (i_buffer[11] << 1) + (i_buffer[11] << 3); // *11
        s1_high_i_q_prod[10] = (i_buffer[10] << 0) + (i_buffer[10] << 1); // *3
        s1_high_i_q_prod[9] = -((i_buffer[9] << 1) + (i_buffer[9] << 2)); // *-6
        s1_high_i_q_prod[8] = -((i_buffer[8] << 2) + (i_buffer[8] << 3)); // *-12
        s1_high_i_q_prod[7] = -((i_buffer[7] << 0) + (i_buffer[7] << 1) + (i_buffer[7] << 2) + (i_buffer[7] << 3)); // *-15
        s1_high_i_q_prod[6] = -((i_buffer[6] << 2) + (i_buffer[6] << 3)); // *-12
        s1_high_i_q_prod[5] = -((i_buffer[5] << 1) + (i_buffer[5] << 2)); // *-6
        s1_high_i_q_prod[4] = (i_buffer[4] << 0) + (i_buffer[4] << 1); // *3
        s1_high_i_q_prod[3] = (i_buffer[3] << 0) + (i_buffer[3] << 1) + (i_buffer[3] << 3); // *11
        s1_high_i_q_prod[2] = (i_buffer[2] << 0) + (i_buffer[2] << 1) + (i_buffer[2] << 2) + (i_buffer[2] << 3); // *15
        s1_high_i_q_prod[1] = (i_buffer[1] << 1) + (i_buffer[1] << 2) + (i_buffer[1] << 3); // *14
        s1_high_i_q_prod[0] = (i_buffer[0] << 3); // *8
        /*verilator lint_on WIDTH*/
    end

    // ========================================
    // BLOCK 8: HIGH TEMPLATE Q × Q (16 products)
    // ========================================
    always_comb begin
        /*verilator lint_off WIDTH*/
        // Template: 0, 8, 14, 15, 11, 3, -6, -12, -15, -12, -6, 3, 11, 15, 14, 8
        s1_high_q_q_prod[15] = 0; // *0
        s1_high_q_q_prod[14] = (q_buffer[14] << 3); // *8
        s1_high_q_q_prod[13] = (q_buffer[13] << 1) + (q_buffer[13] << 2) + (q_buffer[13] << 3); // *14
        s1_high_q_q_prod[12] = (q_buffer[12] << 0) + (q_buffer[12] << 1) + (q_buffer[12] << 2) + (q_buffer[12] << 3); // *15
        s1_high_q_q_prod[11] = (q_buffer[11] << 0) + (q_buffer[11] << 1) + (q_buffer[11] << 3); // *11
        s1_high_q_q_prod[10] = (q_buffer[10] << 0) + (q_buffer[10] << 1); // *3
        s1_high_q_q_prod[9] = -((q_buffer[9] << 1) + (q_buffer[9] << 2)); // *-6
        s1_high_q_q_prod[8] = -((q_buffer[8] << 2) + (q_buffer[8] << 3)); // *-12
        s1_high_q_q_prod[7] = -((q_buffer[7] << 0) + (q_buffer[7] << 1) + (q_buffer[7] << 2) + (q_buffer[7] << 3)); // *-15
        s1_high_q_q_prod[6] = -((q_buffer[6] << 2) + (q_buffer[6] << 3)); // *-12
        s1_high_q_q_prod[5] = -((q_buffer[5] << 1) + (q_buffer[5] << 2)); // *-6
        s1_high_q_q_prod[4] = (q_buffer[4] << 0) + (q_buffer[4] << 1); // *3
        s1_high_q_q_prod[3] = (q_buffer[3] << 0) + (q_buffer[3] << 1) + (q_buffer[3] << 3); // *11
        s1_high_q_q_prod[2] = (q_buffer[2] << 0) + (q_buffer[2] << 1) + (q_buffer[2] << 2) + (q_buffer[2] << 3); // *15
        s1_high_q_q_prod[1] = (q_buffer[1] << 1) + (q_buffer[1] << 2) + (q_buffer[1] << 3); // *14
        s1_high_q_q_prod[0] = (q_buffer[0] << 3); // *8
        /*verilator lint_on WIDTH*/
    end

    // STAGE 2: Partial Sums (16 to 4)
    // Combinational: Sum groups of 4 products
    logic signed [PROD_SUM_WIDTH-1:0] s2_low_i_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_low_q_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_low_i_q_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_low_q_q_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_high_i_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_high_q_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_high_i_q_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_high_q_q_partial [0:3];

    // Registered: Store the partial sums
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_low_i_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_low_q_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_low_i_q_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_low_q_q_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_high_i_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_high_q_i_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_high_i_q_partial [0:3];
    logic signed [PROD_SUM_WIDTH-1:0] s2_reg_high_q_q_partial [0:3];


        // STAGE 2 COMBINATIONAL: Partial Sums (16 → 4)
    always_comb begin
        // ==================== LOW TEMPLATE I ====================
        s2_low_i_i_partial[0] = s1_reg_low_i_i_prod[0] + s1_reg_low_i_i_prod[1] + 
                                s1_reg_low_i_i_prod[2] + s1_reg_low_i_i_prod[3];
        
        s2_low_i_i_partial[1] = s1_reg_low_i_i_prod[4] + s1_reg_low_i_i_prod[5] + 
                                s1_reg_low_i_i_prod[6] + s1_reg_low_i_i_prod[7];
        
        s2_low_i_i_partial[2] = s1_reg_low_i_i_prod[8] + s1_reg_low_i_i_prod[9] + 
                                s1_reg_low_i_i_prod[10] + s1_reg_low_i_i_prod[11];
        
        s2_low_i_i_partial[3] = s1_reg_low_i_i_prod[12] + s1_reg_low_i_i_prod[13] + 
                                s1_reg_low_i_i_prod[14] + s1_reg_low_i_i_prod[15];

        // ==================== LOW TEMPLATE Q_I ====================
        s2_low_q_i_partial[0] = s1_reg_low_q_i_prod[0] + s1_reg_low_q_i_prod[1] + 
                                s1_reg_low_q_i_prod[2] + s1_reg_low_q_i_prod[3];
        
        s2_low_q_i_partial[1] = s1_reg_low_q_i_prod[4] + s1_reg_low_q_i_prod[5] + 
                                s1_reg_low_q_i_prod[6] + s1_reg_low_q_i_prod[7];
        
        s2_low_q_i_partial[2] = s1_reg_low_q_i_prod[8] + s1_reg_low_q_i_prod[9] + 
                                s1_reg_low_q_i_prod[10] + s1_reg_low_q_i_prod[11];
        
        s2_low_q_i_partial[3] = s1_reg_low_q_i_prod[12] + s1_reg_low_q_i_prod[13] + 
                                s1_reg_low_q_i_prod[14] + s1_reg_low_q_i_prod[15];

        // ==================== LOW TEMPLATE I_Q ====================
        s2_low_i_q_partial[0] = s1_reg_low_i_q_prod[0] + s1_reg_low_i_q_prod[1] + 
                                s1_reg_low_i_q_prod[2] + s1_reg_low_i_q_prod[3];
        
        s2_low_i_q_partial[1] = s1_reg_low_i_q_prod[4] + s1_reg_low_i_q_prod[5] + 
                                s1_reg_low_i_q_prod[6] + s1_reg_low_i_q_prod[7];
        
        s2_low_i_q_partial[2] = s1_reg_low_i_q_prod[8] + s1_reg_low_i_q_prod[9] + 
                                s1_reg_low_i_q_prod[10] + s1_reg_low_i_q_prod[11];
        
        s2_low_i_q_partial[3] = s1_reg_low_i_q_prod[12] + s1_reg_low_i_q_prod[13] + 
                                s1_reg_low_i_q_prod[14] + s1_reg_low_i_q_prod[15];

        // ==================== LOW TEMPLATE Q_Q ====================
        s2_low_q_q_partial[0] = s1_reg_low_q_q_prod[0] + s1_reg_low_q_q_prod[1] + 
                                s1_reg_low_q_q_prod[2] + s1_reg_low_q_q_prod[3];
        
        s2_low_q_q_partial[1] = s1_reg_low_q_q_prod[4] + s1_reg_low_q_q_prod[5] + 
                                s1_reg_low_q_q_prod[6] + s1_reg_low_q_q_prod[7];
        
        s2_low_q_q_partial[2] = s1_reg_low_q_q_prod[8] + s1_reg_low_q_q_prod[9] + 
                                s1_reg_low_q_q_prod[10] + s1_reg_low_q_q_prod[11];
        
        s2_low_q_q_partial[3] = s1_reg_low_q_q_prod[12] + s1_reg_low_q_q_prod[13] + 
                                s1_reg_low_q_q_prod[14] + s1_reg_low_q_q_prod[15];

        // ==================== HIGH TEMPLATE I ====================
        s2_high_i_i_partial[0] = s1_reg_high_i_i_prod[0] + s1_reg_high_i_i_prod[1] + 
                                s1_reg_high_i_i_prod[2] + s1_reg_high_i_i_prod[3];
        
        s2_high_i_i_partial[1] = s1_reg_high_i_i_prod[4] + s1_reg_high_i_i_prod[5] + 
                                s1_reg_high_i_i_prod[6] + s1_reg_high_i_i_prod[7];
        
        s2_high_i_i_partial[2] = s1_reg_high_i_i_prod[8] + s1_reg_high_i_i_prod[9] + 
                                s1_reg_high_i_i_prod[10] + s1_reg_high_i_i_prod[11];
        
        s2_high_i_i_partial[3] = s1_reg_high_i_i_prod[12] + s1_reg_high_i_i_prod[13] + 
                                s1_reg_high_i_i_prod[14] + s1_reg_high_i_i_prod[15];

        // ==================== HIGH TEMPLATE Q_I ====================
        s2_high_q_i_partial[0] = s1_reg_high_q_i_prod[0] + s1_reg_high_q_i_prod[1] + 
                                s1_reg_high_q_i_prod[2] + s1_reg_high_q_i_prod[3];
        
        s2_high_q_i_partial[1] = s1_reg_high_q_i_prod[4] + s1_reg_high_q_i_prod[5] + 
                                s1_reg_high_q_i_prod[6] + s1_reg_high_q_i_prod[7];
        
        s2_high_q_i_partial[2] = s1_reg_high_q_i_prod[8] + s1_reg_high_q_i_prod[9] + 
                                s1_reg_high_q_i_prod[10] + s1_reg_high_q_i_prod[11];
        
        s2_high_q_i_partial[3] = s1_reg_high_q_i_prod[12] + s1_reg_high_q_i_prod[13] + 
                                s1_reg_high_q_i_prod[14] + s1_reg_high_q_i_prod[15];

        // ==================== HIGH TEMPLATE I_Q ====================
        s2_high_i_q_partial[0] = s1_reg_high_i_q_prod[0] + s1_reg_high_i_q_prod[1] + 
                                s1_reg_high_i_q_prod[2] + s1_reg_high_i_q_prod[3];
        
        s2_high_i_q_partial[1] = s1_reg_high_i_q_prod[4] + s1_reg_high_i_q_prod[5] + 
                                s1_reg_high_i_q_prod[6] + s1_reg_high_i_q_prod[7];
        
        s2_high_i_q_partial[2] = s1_reg_high_i_q_prod[8] + s1_reg_high_i_q_prod[9] + 
                                s1_reg_high_i_q_prod[10] + s1_reg_high_i_q_prod[11];
        
        s2_high_i_q_partial[3] = s1_reg_high_i_q_prod[12] + s1_reg_high_i_q_prod[13] + 
                                s1_reg_high_i_q_prod[14] + s1_reg_high_i_q_prod[15];

        // ==================== HIGH TEMPLATE Q_Q ====================
        s2_high_q_q_partial[0] = s1_reg_high_q_q_prod[0] + s1_reg_high_q_q_prod[1] + 
                                s1_reg_high_q_q_prod[2] + s1_reg_high_q_q_prod[3];
        
        s2_high_q_q_partial[1] = s1_reg_high_q_q_prod[4] + s1_reg_high_q_q_prod[5] + 
                                s1_reg_high_q_q_prod[6] + s1_reg_high_q_q_prod[7];
        
        s2_high_q_q_partial[2] = s1_reg_high_q_q_prod[8] + s1_reg_high_q_q_prod[9] + 
                                s1_reg_high_q_q_prod[10] + s1_reg_high_q_q_prod[11];
        
        s2_high_q_q_partial[3] = s1_reg_high_q_q_prod[12] + s1_reg_high_q_q_prod[13] + 
                                s1_reg_high_q_q_prod[14] + s1_reg_high_q_q_prod[15];
    end


    // STAGE 3: Final Correlation Sums (4 → 1)
    // Combinational: Sum the 4 partial sums
    logic signed [PROD_SUM_WIDTH-1:0] s3_low_i_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_low_q_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_low_i_q_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_low_q_q_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_high_i_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_high_q_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_high_i_q_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_high_q_q_sum;

    // Registered: Store the final correlation sums
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_low_i_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_low_q_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_low_i_q_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_low_q_q_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_high_i_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_high_q_i_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_high_i_q_sum;
    logic signed [PROD_SUM_WIDTH-1:0] s3_reg_high_q_q_sum;


    // STAGE 3 COMBINATIONAL: Final Correlation Sums
    always_comb begin
        // Sum the 4 partial sums to get final correlation
        s3_low_i_i_sum = s2_reg_low_i_i_partial[0] + s2_reg_low_i_i_partial[1] + 
                        s2_reg_low_i_i_partial[2] + s2_reg_low_i_i_partial[3];
        
        s3_low_q_i_sum = s2_reg_low_q_i_partial[0] + s2_reg_low_q_i_partial[1] + 
                        s2_reg_low_q_i_partial[2] + s2_reg_low_q_i_partial[3];
        
        s3_low_i_q_sum = s2_reg_low_i_q_partial[0] + s2_reg_low_i_q_partial[1] + 
                        s2_reg_low_i_q_partial[2] + s2_reg_low_i_q_partial[3];
        
        s3_low_q_q_sum = s2_reg_low_q_q_partial[0] + s2_reg_low_q_q_partial[1] + 
                        s2_reg_low_q_q_partial[2] + s2_reg_low_q_q_partial[3];
        
        s3_high_i_i_sum = s2_reg_high_i_i_partial[0] + s2_reg_high_i_i_partial[1] + 
                        s2_reg_high_i_i_partial[2] + s2_reg_high_i_i_partial[3];
        
        s3_high_q_i_sum = s2_reg_high_q_i_partial[0] + s2_reg_high_q_i_partial[1] + 
                        s2_reg_high_q_i_partial[2] + s2_reg_high_q_i_partial[3];
        
        s3_high_i_q_sum = s2_reg_high_i_q_partial[0] + s2_reg_high_i_q_partial[1] + 
                        s2_reg_high_i_q_partial[2] + s2_reg_high_i_q_partial[3];
        
        s3_high_q_q_sum = s2_reg_high_q_q_partial[0] + s2_reg_high_q_q_partial[1] + 
                        s2_reg_high_q_q_partial[2] + s2_reg_high_q_q_partial[3];
    end

    // Combinational: Square each correlation sum
    logic signed [SQR_WIDTH-1:0] s4_low_i_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_low_q_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_low_i_q_sqr;
    logic signed [SQR_WIDTH-1:0] s4_low_q_q_sqr;
    logic signed [SQR_WIDTH-1:0] s4_high_i_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_high_q_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_high_i_q_sqr;
    logic signed [SQR_WIDTH-1:0] s4_high_q_q_sqr;

    // Registered: Store the squared values
    logic signed [SQR_WIDTH-1:0] s4_reg_low_i_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_low_q_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_low_i_q_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_low_q_q_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_high_i_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_high_q_i_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_high_i_q_sqr;
    logic signed [SQR_WIDTH-1:0] s4_reg_high_q_q_sqr;


        // STAGE 4 COMBINATIONAL: Squaring
    always_comb begin
        s4_low_i_i_sqr = s3_reg_low_i_i_sum * s3_reg_low_i_i_sum;
    end

    // Block 2: Low Q×I  
    always_comb begin
        s4_low_q_i_sqr = s3_reg_low_q_i_sum * s3_reg_low_q_i_sum;
    end

    // Block 3: Low I×Q
    always_comb begin
        s4_low_i_q_sqr = s3_reg_low_i_q_sum * s3_reg_low_i_q_sum;
    end

    // Block 4: Low Q×Q
    always_comb begin
        s4_low_q_q_sqr = s3_reg_low_q_q_sum * s3_reg_low_q_q_sum;
    end

    // Block 5: High I×I
    always_comb begin
        s4_high_i_i_sqr = s3_reg_high_i_i_sum * s3_reg_high_i_i_sum;
    end

    // Block 6: High Q×I
    always_comb begin
        s4_high_q_i_sqr = s3_reg_high_q_i_sum * s3_reg_high_q_i_sum;
    end

    // Block 7: High I×Q
    always_comb begin
        s4_high_i_q_sqr = s3_reg_high_i_q_sum * s3_reg_high_i_q_sum;
    end

    // Block 8: High Q×Q
    always_comb begin
        s4_high_q_q_sqr = s3_reg_high_q_q_sum * s3_reg_high_q_q_sum;
    end
    // STAGE 5: Final Scores and Comparison
    // Combinational: Sum the 4 squared values for each score
    logic signed [SCORE_WIDTH-1:0] s5_low_score;
    logic signed [SCORE_WIDTH-1:0] s5_high_score;

    // Registered: Store the final scores
    logic signed [SCORE_WIDTH-1:0] s5_reg_low_score;
    logic signed [SCORE_WIDTH-1:0] s5_reg_high_score;

    always_comb begin
        // Low score = sum of 4 low template squared correlations
        s5_low_score = s4_reg_low_i_i_sqr + s4_reg_low_q_i_sqr + 
                    s4_reg_low_i_q_sqr + s4_reg_low_q_q_sqr;
        
        // High score = sum of 4 high template squared correlations
        s5_high_score = s4_reg_high_i_i_sqr + s4_reg_high_q_i_sqr + 
                        s4_reg_high_i_q_sqr + s4_reg_high_q_q_sqr;
    end

    logic demodulated_bit_reg;
    
    always_ff @(posedge clk or negedge resetn) begin
        if (~resetn) begin
            demodulated_bit_reg <= 1'b0;
        end else if (en) begin
            demodulated_bit_reg <= (s5_reg_high_score > s5_reg_low_score);
        end
    end
    
    assign demodulated_bit = demodulated_bit_reg;
    // pipeline update
    always_ff @(posedge clk or negedge resetn) begin
        if (~resetn) begin
            // ===== STAGE 1 RESET =====
            for (int i = 0; i < 16; i++) begin
                s1_reg_low_i_i_prod[i] <= 0;
                s1_reg_low_q_i_prod[i] <= 0;
                s1_reg_low_i_q_prod[i] <= 0;
                s1_reg_low_q_q_prod[i] <= 0;
                s1_reg_high_i_i_prod[i] <= 0;
                s1_reg_high_q_i_prod[i] <= 0;
                s1_reg_high_i_q_prod[i] <= 0;
                s1_reg_high_q_q_prod[i] <= 0;
            end
            
            // ===== STAGE 2 RESET =====
            for (int i = 0; i < 4; i++) begin
                s2_reg_low_i_i_partial[i] <= 0;
                s2_reg_low_q_i_partial[i] <= 0;
                s2_reg_low_i_q_partial[i] <= 0;
                s2_reg_low_q_q_partial[i] <= 0;
                s2_reg_high_i_i_partial[i] <= 0;
                s2_reg_high_q_i_partial[i] <= 0;
                s2_reg_high_i_q_partial[i] <= 0;
                s2_reg_high_q_q_partial[i] <= 0;
            end
            
            // ===== STAGE 3 RESET =====
            s3_reg_low_i_i_sum <= 0;
            s3_reg_low_q_i_sum <= 0;
            s3_reg_low_i_q_sum <= 0;
            s3_reg_low_q_q_sum <= 0;
            s3_reg_high_i_i_sum <= 0;
            s3_reg_high_q_i_sum <= 0;
            s3_reg_high_i_q_sum <= 0;
            s3_reg_high_q_q_sum <= 0;
            
            // ===== STAGE 4 RESET =====
            s4_reg_low_i_i_sqr <= 0;
            s4_reg_low_q_i_sqr <= 0;
            s4_reg_low_i_q_sqr <= 0;
            s4_reg_low_q_q_sqr <= 0;
            s4_reg_high_i_i_sqr <= 0;
            s4_reg_high_q_i_sqr <= 0;
            s4_reg_high_i_q_sqr <= 0;
            s4_reg_high_q_q_sqr <= 0;
            
            // ===== STAGE 5 RESET =====
            s5_reg_low_score <= 0;
            s5_reg_high_score <= 0;
            
        end else if (en) begin
            // ===== STAGE 1 UPDATE =====
            for (int i = 0; i < 16; i++) begin
                s1_reg_low_i_i_prod[i] <= s1_low_i_i_prod[i];
                s1_reg_low_q_i_prod[i] <= s1_low_q_i_prod[i];
                s1_reg_low_i_q_prod[i] <= s1_low_i_q_prod[i];
                s1_reg_low_q_q_prod[i] <= s1_low_q_q_prod[i];
                s1_reg_high_i_i_prod[i] <= s1_high_i_i_prod[i];
                s1_reg_high_q_i_prod[i] <= s1_high_q_i_prod[i];
                s1_reg_high_i_q_prod[i] <= s1_high_i_q_prod[i];
                s1_reg_high_q_q_prod[i] <= s1_high_q_q_prod[i];
            end
            
            // ===== STAGE 2 UPDATE =====
            for (int i = 0; i < 4; i++) begin
                s2_reg_low_i_i_partial[i] <= s2_low_i_i_partial[i];
                s2_reg_low_q_i_partial[i] <= s2_low_q_i_partial[i];
                s2_reg_low_i_q_partial[i] <= s2_low_i_q_partial[i];
                s2_reg_low_q_q_partial[i] <= s2_low_q_q_partial[i];
                s2_reg_high_i_i_partial[i] <= s2_high_i_i_partial[i];
                s2_reg_high_q_i_partial[i] <= s2_high_q_i_partial[i];
                s2_reg_high_i_q_partial[i] <= s2_high_i_q_partial[i];
                s2_reg_high_q_q_partial[i] <= s2_high_q_q_partial[i];
            end
            
            // ===== STAGE 3 UPDATE =====
            s3_reg_low_i_i_sum <= s3_low_i_i_sum;
            s3_reg_low_q_i_sum <= s3_low_q_i_sum;
            s3_reg_low_i_q_sum <= s3_low_i_q_sum;
            s3_reg_low_q_q_sum <= s3_low_q_q_sum;
            s3_reg_high_i_i_sum <= s3_high_i_i_sum;
            s3_reg_high_q_i_sum <= s3_high_q_i_sum;
            s3_reg_high_i_q_sum <= s3_high_i_q_sum;
            s3_reg_high_q_q_sum <= s3_high_q_q_sum;
            
            // ===== STAGE 4 UPDATE =====
            s4_reg_low_i_i_sqr <= s4_low_i_i_sqr;
            s4_reg_low_q_i_sqr <= s4_low_q_i_sqr;
            s4_reg_low_i_q_sqr <= s4_low_i_q_sqr;
            s4_reg_low_q_q_sqr <= s4_low_q_q_sqr;
            s4_reg_high_i_i_sqr <= s4_high_i_i_sqr;
            s4_reg_high_q_i_sqr <= s4_high_q_i_sqr;
            s4_reg_high_i_q_sqr <= s4_high_i_q_sqr;
            s4_reg_high_q_q_sqr <= s4_high_q_q_sqr;
            
            // ===== STAGE 5 UPDATE =====
            s5_reg_low_score <= s5_low_score;
            s5_reg_high_score <= s5_high_score;
        end
    end

endmodule
